spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: username
    password: password
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
application:
  security:
    jwt:
      secret-key: sG9aX8e4f2b3V0lZ5dK6hN8jP1rS3uX7cV2eM5oB9nT6wY4zQ1g
      expiration: 86400000
      token-prefix: Bearer
      header-string: Authorization
  mailing:
    frontend: http://localhost:4200/activate-account

server:
  port: 8088
logging:
  level:
    org:
      springframework: debug
